#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackAtHome.AndroidClient.Resource", IsApplication=true)]

namespace HackAtHome.AndroidClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int App = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000f
			public const int buttonValidateLogin = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int editTextEmailLogin = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int editTextPasswordLogin = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int imageViewActivityDetail = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout1 = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout2 = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout3 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout4 = 2131034129;
			
			// aapt resource value: 0x7f050002
			public const int listViewActiviesList = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int textView1 = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int textView2 = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int textViewDescriptionActivityDetail = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int textViewNameActivitiesList = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int textViewNameActivityDetail = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int textViewStatusActivitiesListItem = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int textViewStatusActivityDetail = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int textViewTitleActiviesListItem = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int textViewTitleActivityDetail = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivitiesList = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivitiesListItems = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActivityDetail = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int Cargando = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int ErrorAutenticacionCampos = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int ErrorAutenticacionInterno = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ErrorAutenticacionInvalido = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int ErrorAutenticacionTitulo = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int ErrorDetalleActividadInterno = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int ErrorDetalleActividadTitulo = 2130968588;
			
			// aapt resource value: 0x7f040008
			public const int ErrorListaActividadesInterno = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int ErrorListaActividadesTitulo = 2130968587;
			
			// aapt resource value: 0x7f040001
			public const int contrasenia = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int correo = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int descripcion = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int evidencias = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int validar = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
